<a href="https://colab.research.google.com/github/abdulqadoos861/GetData_practice_ML/blob/main/ML_pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import pandas as pd
import numpy as np
import seaborn as sns

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier

In [62]:
df =sns.load_dataset("titanic")
df.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [63]:
# survived , pclass , sex , age, sibsp,parch, fare, embarked
df.drop(columns=["class","who","adult_male",	"deck",	"embark_town",	"alive","alone"] , inplace=True)

In [64]:
df

     survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [65]:
X = df.drop(columns=["survived"])
Y = df["survived"]

In [66]:
# Step1 split train test
X_train , X_test , Y_train , Y_test = train_test_split(X , Y, test_size=0.2 , random_state=1)
X_train.head()

     pclass     sex   age  sibsp  parch     fare embarked
301       3    male   NaN      2      0  23.2500        Q
309       1  female  30.0      0      0  56.9292        C
516       2  female  34.0      0      0  10.5000        S
120       2    male  21.0      2      0  73.5000        S
570       2    male  62.0      0      0  10.5000        S

In [67]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [68]:
# Step2 Apply Transofrmation.
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy="most_frequent")

X_train_age = si_age.fit_transform(X_train[['age']])
X_train_embarked = si_embarked.fit_transform(X_train[['embarked']])

X_test_age = si_age.transform(X_test[['age']])
X_test_embarked = si_embarked.transform(X_test[['embarked']])
#

In [69]:
X_train_age

array([[30.16623239],
       [30.        ],
       [34.        ],
       [21.        ],
       [62.        ],
       [29.        ],
       [18.        ],
       [30.16623239],
       [18.        ],
       [30.16623239],
       [44.        ],
       [30.16623239],
       [45.        ],
       [30.16623239],
       [15.        ],
       [ 9.        ],
       [38.        ],
       [30.16623239],
       [19.        ],
       [24.5       ],
       [71.        ],
       [17.        ],
       [53.        ],
       [30.16623239],
       [23.        ],
       [37.        ],
       [24.        ],
       [51.        ],
       [25.        ],
       [30.16623239],
       [37.        ],
       [32.        ],
       [ 4.        ],
       [28.5       ],
       [11.        ],
       [32.        ],
       [35.        ],
       [30.16623239],
       [17.        ],
       [33.        ],
       [56.        ],
       [30.16623239],
       [30.16623239],
       [52.        ],
       [42.        ],
       [30.16623239],
       [49.        ],
       [19.        ],
       [19.        ],
       [27.        ],
       [38.        ],
       [ 2.        ],
       [12.        ],
       [ 0.42      ],
       [34.        ],
       [38.        ],
       [30.16623239],
       [30.16623239],
       [30.16623239],
       [17.        ],
       [22.        ],
       [60.        ],
       [23.        ],
       [30.        ],
       [32.        ],
       [44.        ],
       [31.        ],
       [29.        ],
       [34.        ],
       [48.        ],
       [33.        ],
       [41.        ],
       [29.        ],
       [36.        ],
       [11.        ],
       [58.        ],
       [18.        ],
       [44.        ],
       [40.        ],
       [31.        ],
       [ 9.        ],
       [13.        ],
       [30.16623239],
       [30.16623239],
       [24.        ],
       [27.        ],
       [33.        ],
       [25.        ],
       [46.        ],
       [17.        ],
       [28.        ],
       [30.16623239],
       [20.        ],
       [30.16623239],
       [47.        ],
       [36.        ],
       [16.        ],
       [ 5.        ],
       [25.        ],
       [39.        ],
       [18.        ],
       [40.        ],
       [24.        ],
       [18.        ],
       [19.        ],
       [17.        ],
       [30.        ],
       [24.        ],
       [30.16623239],
       [24.        ],
       [39.        ],
       [ 2.        ],
       [21.        ],
       [43.        ],
       [18.        ],
       [30.16623239],
       [54.        ],
       [14.        ],
       [30.16623239],
       [32.        ],
       [30.16623239],
       [23.        ],
       [37.        ],
       [ 1.        ],
       [22.        ],
       [33.        ],
       [43.        ],
       [ 4.        ],
       [30.16623239],
       [24.        ],
       [ 1.        ],
       [30.16623239],
       [30.16623239],
       [58.        ],
       [30.16623239],
       [28.        ],
       [ 9.        ],
       [50.        ],
       [21.        ],
       [31.        ],
       [28.        ],
       [26.        ],
       [21.        ],
       [14.        ],
       [21.        ],
       [32.        ],
       [19.        ],
       [ 0.92      ],
       [30.16623239],
       [30.16623239],
       [ 8.        ],
       [ 2.        ],
       [33.        ],
       [ 9.        ],
       [23.        ],
       [70.5       ],
       [36.        ],
       [30.16623239],
       [39.        ],
       [30.16623239],
       [30.16623239],
       [32.        ],
       [17.        ],
       [22.        ],
       [45.        ],
       [18.        ],
       [20.        ],
       [ 4.        ],
       [20.        ],
       [30.        ],
       [21.        ],
       [40.        ],
       [17.        ],
       [30.16623239],
       [65.        ],
       [60.        ],
       [ 0.83      ],
       [30.16623239],
       [27.        ],
       [27.        ],
       [20.        ],
       [20.        ],
       [30.16623239],
       [21.        ],
       [30.16623239],
       [44.        ],
       [ 9.        ],
       [30.16623239],
       [22.        ],
       [20.5       ],
       [25.        ],
       [24.        ],
       [50.        ],
       [22.        ],
       [14.        ],
       [35.        ],
       [62.        ],
       [42.        ],
       [36.        ],
       [19.        ],
       [30.16623239],
       [18.        ],
       [29.        ],
       [24.        ],
       [70.        ],
       [30.16623239],
       [42.        ],
       [18.        ],
       [49.        ],
       [29.        ],
       [ 3.        ],
       [34.        ],
       [32.5       ],
       [ 0.67      ],
       [21.        ],
       [18.        ],
       [30.16623239],
       [36.        ],
       [30.16623239],
       [29.        ],
       [30.16623239],
       [26.        ],
       [19.        ],
       [54.        ],
       [14.        ],
       [35.        ],
       [66.        ],
       [30.16623239],
       [28.        ],
       [35.        ],
       [30.16623239],
       [65.        ],
       [ 4.        ],
       [34.        ],
       [31.        ],
       [40.        ],
       [44.        ],
       [16.        ],
       [30.16623239],
       [36.        ],
       [30.16623239],
       [33.        ],
       [30.16623239],
       [32.        ],
       [30.16623239],
       [26.        ],
       [28.        ],
       [30.16623239],
       [30.16623239],
       [15.        ],
       [60.        ],
       [16.        ],
       [20.        ],
       [30.16623239],
       [30.16623239],
       [22.        ],
       [50.        ],
       [33.        ],
       [ 3.        ],
       [30.16623239],
       [63.        ],
       [16.        ],
       [40.5       ],
       [31.        ],
       [30.16623239],
       [30.16623239],
       [28.        ],
       [24.        ],
       [74.        ],
       [22.        ],
       [44.        ],
       [ 0.83      ],
       [26.        ],
       [39.        ],
       [21.        ],
       [56.        ],
       [30.16623239],
       [30.16623239],
       [29.        ],
       [36.        ],
       [17.        ],
       [30.16623239],
       [30.16623239],
       [50.        ],
       [32.        ],
       [30.16623239],
       [25.        ],
       [24.        ],
       [50.        ],
       [19.        ],
       [16.        ],
       [47.        ],
       [27.        ],
       [50.        ],
       [42.        ],
       [30.16623239],
       [25.        ],
       [40.        ],
       [40.        ],
       [41.        ],
       [ 4.        ],
       [22.        ],
       [30.        ],
       [32.        ],
       [41.        ],
       [17.        ],
       [24.        ],
       [30.5       ],
       [30.16623239],
       [27.        ],
       [70.        ],
       [21.        ],
       [49.        ],
       [30.16623239],
       [16.        ],
       [19.        ],
       [21.        ],
       [30.        ],
       [30.16623239],
       [23.        ],
       [29.        ],
       [30.16623239],
       [20.        ],
       [35.        ],
       [50.        ],
       [30.16623239],
       [47.        ],
       [36.        ],
       [19.        ],
       [19.        ],
       [10.        ],
       [45.5       ],
       [25.        ],
       [24.        ],
       [38.        ],
       [30.16623239],
       [30.        ],
       [ 8.        ],
       [39.        ],
       [59.        ],
       [25.        ],
       [34.        ],
       [43.        ],
       [47.        ],
       [30.16623239],
       [19.        ],
       [42.        ],
       [40.        ],
       [30.16623239],
       [51.        ],
       [22.        ],
       [31.        ],
       [30.16623239],
       [36.        ],
       [ 9.        ],
       [46.        ],
       [31.        ],
       [25.        ],
       [36.        ],
       [26.        ],
       [30.        ],
       [41.        ],
       [30.16623239],
       [30.16623239],
       [21.        ],
       [30.16623239],
       [28.        ],
       [22.        ],
       [30.16623239],
       [28.        ],
       [45.        ],
       [30.        ],
       [20.        ],
       [30.16623239],
       [26.        ],
       [54.        ],
       [28.        ],
       [39.        ],
       [51.        ],
       [33.        ],
       [ 1.        ],
       [13.        ],
       [ 6.        ],
       [28.5       ],
       [28.        ],
       [45.        ],
       [30.16623239],
       [32.        ],
       [35.        ],
       [30.16623239],
       [30.16623239],
       [39.        ],
       [24.        ],
       [30.        ],
       [38.        ],
       [54.        ],
       [22.        ],
       [30.        ],
       [30.16623239],
       [ 4.        ],
       [18.        ],
       [31.        ],
       [48.        ],
       [24.        ],
       [28.        ],
       [26.        ],
       [22.        ],
       [30.16623239],
       [18.        ],
       [64.        ],
       [18.        ],
       [51.        ],
       [32.        ],
       [48.        ],
       [30.16623239],
       [30.16623239],
       [19.        ],
       [50.        ],
       [16.        ],
       [33.        ],
       [23.        ],
       [16.        ],
       [45.        ],
       [20.        ],
       [42.        ],
       [56.        ],
       [30.16623239],
       [30.16623239],
       [ 3.        ],
       [51.        ],
       [32.5       ],
       [16.        ],
       [21.        ],
       [63.        ],
       [30.16623239],
       [28.        ],
       [30.16623239],
       [ 9.        ],
       [26.        ],
       [30.16623239],
       [18.        ],
       [30.16623239],
       [35.        ],
       [61.        ],
       [50.        ],
       [38.        ],
       [17.        ],
       [45.        ],
       [19.        ],
       [32.        ],
       [17.        ],
       [40.        ],
       [30.16623239],
       [48.        ],
       [30.        ],
       [19.        ],
       [30.        ],
       [27.        ],
       [39.        ],
       [30.        ],
       [30.16623239],
       [19.        ],
       [28.        ],
       [26.        ],
       [30.16623239],
       [30.16623239],
       [29.        ],
       [21.        ],
       [21.        ],
       [26.        ],
       [29.        ],
       [24.        ],
       [30.16623239],
       [25.        ],
       [19.        ],
       [20.        ],
       [ 8.        ],
       [35.        ],
       [27.        ],
       [28.        ],
       [52.        ],
       [31.        ],
       [30.16623239],
       [30.        ],
       [30.16623239],
       [30.16623239],
       [30.16623239],
       [19.        ],
       [30.16623239],
       [51.        ],
       [30.16623239],
       [22.        ],
       [30.16623239],
       [ 4.        ],
       [25.        ],
       [27.        ],
       [30.16623239],
       [18.        ],
       [33.        ],
       [ 2.        ],
       [64.        ],
       [29.        ],
       [30.16623239],
       [ 4.        ],
       [30.16623239],
       [30.16623239],
       [21.        ],
       [30.        ],
       [30.16623239],
       [ 4.        ],
       [24.        ],
       [30.16623239],
       [30.16623239],
       [47.        ],
       [18.        ],
       [25.        ],
       [30.16623239],
       [ 8.        ],
       [15.        ],
       [30.        ],
       [30.16623239],
       [23.5       ],
       [34.        ],
       [30.16623239],
       [36.        ],
       [24.        ],
       [36.        ],
       [37.        ],
       [45.        ],
       [44.        ],
       [19.        ],
       [26.        ],
       [22.        ],
       [41.        ],
       [39.        ],
       [27.        ],
       [18.        ],
       [34.        ],
       [29.        ],
       [34.        ],
       [30.16623239],
       [54.        ],
       [ 1.        ],
       [20.        ],
       [30.16623239],
       [25.        ],
       [40.        ],
       [57.        ],
       [30.16623239],
       [ 7.        ],
       [80.        ],
       [35.        ],
       [61.        ],
       [26.        ],
       [30.16623239],
       [19.        ],
       [30.16623239],
       [36.        ],
       [45.        ],
       [30.16623239],
       [30.16623239],
       [25.        ],
       [60.        ],
       [16.        ],
       [24.        ],
       [30.16623239],
       [55.        ],
       [33.        ],
       [45.        ],
       [34.        ],
       [ 9.        ],
       [36.        ],
       [30.        ],
       [ 3.        ],
       [30.16623239],
       [34.        ],
       [50.        ],
       [34.        ],
       [52.        ],
       [55.5       ],
       [31.        ],
       [ 4.        ],
       [35.        ],
       [71.        ],
       [24.        ],
       [56.        ],
       [33.        ],
       [32.        ],
       [33.        ],
       [34.5       ],
       [17.        ],
       [18.        ],
       [38.        ],
       [25.        ],
       [48.        ],
       [30.16623239],
       [40.        ],
       [27.        ],
       [42.        ],
       [23.        ],
       [24.        ],
       [20.        ],
       [ 0.75      ],
       [30.16623239],
       [54.        ],
       [34.        ],
       [30.        ],
       [48.        ],
       [24.        ],
       [27.        ],
       [52.        ],
       [22.        ],
       [30.16623239],
       [19.        ],
       [32.        ],
       [47.        ],
       [ 3.        ],
       [22.        ],
       [30.16623239],
       [30.16623239],
       [ 6.        ],
       [24.        ],
       [35.        ],
       [30.16623239],
       [30.        ],
       [42.        ],
       [30.16623239],
       [30.16623239],
       [36.        ],
       [32.        ],
       [51.        ],
       [22.        ],
       [ 1.        ],
       [35.        ],
       [30.16623239],
       [42.        ],
       [ 5.        ],
       [15.        ],
       [34.        ],
       [32.        ],
       [16.        ],
       [38.        ],
       [30.16623239],
       [30.16623239],
       [38.        ],
       [30.16623239],
       [30.16623239],
       [55.        ],
       [30.16623239],
       [ 2.        ],
       [42.        ],
       [29.        ],
       [52.        ],
       [30.16623239],
       [22.        ],
       [ 3.        ],
       [30.16623239],
       [30.16623239],
       [47.        ],
       [44.        ],
       [40.        ],
       [30.16623239],
       [36.        ],
       [16.        ],
       [11.        ],
       [65.        ],
       [30.16623239],
       [30.16623239],
       [21.        ],
       [30.16623239],
       [25.        ],
       [30.16623239],
       [40.        ],
       [24.        ],
       [54.        ],
       [28.        ],
       [30.        ],
       [62.        ],
       [40.        ],
       [ 2.        ],
       [23.        ],
       [22.        ],
       [16.        ],
       [22.        ],
       [37.        ],
       [23.        ],
       [31.        ],
       [25.        ],
       [28.        ],
       [23.        ],
       [43.        ],
       [30.16623239],
       [62.        ],
       [30.16623239],
       [38.        ],
       [41.        ],
       [45.        ],
       [30.        ],
       [28.        ],
       [36.        ],
       [28.        ],
       [31.        ],
       [36.        ],
       [45.        ],
       [18.        ],
       [35.        ],
       [48.        ],
       [19.        ],
       [30.5       ],
       [21.        ],
       [30.16623239],
       [21.        ]])

In [70]:
# Encoding
# One Hot encoding because these columns are minimal coulmns not ordinal coulmns.
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
ohe_embarked = OneHotEncoder(sparse_output=False , handle_unknown= "ignore")

X_train_ohe_sex = ohe_sex.fit_transform(X_train[['sex']])
X_train_ohe_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_ohe_sex = ohe_sex.transform(X_test[['sex']])
X_test_ohe_embarked = ohe_embarked.transform(X_test_embarked)

In [71]:
X_train = X_train.drop(columns = ['sex','age','embarked'])
X_test = X_test.drop(columns = ['sex','age','embarked'])
X_train_transformed = np.concatenate((X_train , X_train_age ,X_train_ohe_sex, X_train_ohe_embarked),axis=1 )
X_test_transformed = np.concatenate((X_test,X_test_age ,X_test_ohe_sex, X_test_ohe_embarked) , axis=1 )

In [72]:
#  now training model
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed , Y_train)
y_pred = clf.predict(X_test_transformed)

In [73]:
import sklearn.metrics as metrics
print(metrics.accuracy_score(Y_test , y_pred))

0.7653631284916201